name: tw_core
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-0 <3.0.0"

dependencies:
  asn1lib: ^1.1.0
  bloc: 7.2.0
  cache:
    path: packages/cache
  cloud_firestore: ^3.1.4
  dartz: ^0.10.1
  dio: ^4.0.4
  dotted_border: ^2.0.0+2
  encrypt: ^5.0.1
  equatable: ^2.0.3
  file_picker: ^4.2.7
  firebase_auth: ^3.3.3
  firebase_dynamic_links: ^4.0.2
  firebase_storage: ^10.2.3
  flutter:
    sdk: flutter
  flutter_bloc: 7.3.0
  flutter_svg: ^1.0.0
  flutter_typeahead: ^3.2.4
  freezed_annotation: ^1.1.0
  geolocator: ^8.0.1
  google_sign_in: ^5.0.5
  http: ^0.13.3
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  json_annotation: ^4.4.0
  kt_dart: ^0.10.0
  open_file: ^3.2.1
  path: ^1.8.0
  path_provider: ^2.0.8
  pdf: ^3.6.0
  pointycastle: ^3.5.0
  secure_random: ^1.0.1
  shared_preferences: ^2.0.12
  sign_in_with_apple: ^3.2.0

dependency_overrides:
  meta: ^1.4.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
